# 自动生成：从 common.j/blizzard.j 提取的 native 参数对象类别 & BJ 隐式引用码。
# 由 build_jass_natives.py 生成，重跑可刷新。请勿手改。

# native名 → 对象分类（None=有对象码参数但多类/不确定）
NATIVE_OBJ_FUNCS = {
    'UnitId2String': '单位',
    'AbilityId2String': '技能',
    'CreateDestructable': '可破坏物',
    'CreateDestructableZ': '可破坏物',
    'CreateDeadDestructable': '可破坏物',
    'CreateDeadDestructableZ': '可破坏物',
    'CreateItem': '物品',
    'IsItemIdPowerup': '物品',
    'IsItemIdSellable': '物品',
    'IsItemIdPawnable': '物品',
    'SetItemDropID': '单位',
    'CreateUnit': '单位',
    'CreateUnitAtLoc': '单位',
    'CreateCorpse': '单位',
    'SelectHeroSkill': '技能',
    'GetUnitAbilityLevel': '技能',
    'DecUnitAbilityLevel': '技能',
    'IncUnitAbilityLevel': '技能',
    'SetUnitAbilityLevel': '技能',
    'UnitAddItemById': '物品',
    'UnitAddItemToSlotById': '物品',
    'GetFoodMade': '单位',
    'GetFoodUsed': '单位',
    'IsHeroUnitId': '单位',
    'IsUnitIdType': '单位',
    'UnitAddAbility': '技能',
    'UnitRemoveAbility': '技能',
    'UnitMakeAbilityPermanent': '技能',
    'UnitApplyTimedLife': '增益',
    'IssueBuildOrderById': '单位',
    'IssueNeutralImmediateOrderById': '单位',
    'IssueNeutralPointOrderById': '单位',
    'IssueNeutralTargetOrderById': '单位',
    'AddItemToAllStock': '物品',
    'AddItemToStock': '物品',
    'AddUnitToAllStock': '单位',
    'AddUnitToStock': '单位',
    'RemoveItemFromAllStock': '物品',
    'RemoveItemFromStock': '物品',
    'RemoveUnitFromAllStock': '单位',
    'RemoveUnitFromStock': '单位',
    'SetPlayerTechMaxAllowed': '科技',
    'GetPlayerTechMaxAllowed': '科技',
    'AddPlayerTechResearched': '科技',
    'SetPlayerTechResearched': '科技',
    'GetPlayerTechResearched': '科技',
    'GetPlayerTechCount': '科技',
    'SetPlayerAbilityAvailable': '技能',
    'UnitPoolAddUnitType': '单位',
    'UnitPoolRemoveUnitType': '单位',
    'ItemPoolAddItemType': '物品',
    'ItemPoolRemoveItemType': '物品',
    'SetCinematicScene': '单位',
    'AddSpellEffectById': '技能',
    'AddSpellEffectByIdLoc': '技能',
    'AddSpellEffectTargetById': '技能',
    'GetAbilityEffectById': '技能',
    'GetAbilitySoundById': '技能',
}

# 暴雪 BJ 函数 → 函数体里硬编码的对象码（脚本调用即隐式引用这些基础对象）
BJ_FUNC_CODES = {
    'MeleeStartingUnitsHuman': ['htow', 'hpea', 'Amic', 'Hamg', 'Hmkg', 'Hpal', 'Hblm'],
    'MeleeStartingUnitsOrc': ['ogre', 'opeo', 'Obla', 'Ofar', 'Otch', 'Oshd'],
    'MeleeStartingUnitsUndead': ['unpl', 'ugho', 'uaco', 'Udea', 'Udre', 'Ulic', 'Ucrl'],
    'MeleeStartingUnitsNightElf': ['etol', 'ewsp', 'Edem', 'Ekee', 'Emoo', 'Ewar'],
    'MeleeStartingHeroLimit': ['Hamg', 'Hmkg', 'Hpal', 'Hblm', 'Obla', 'Ofar', 'Otch', 'Oshd', 'Edem', 'Ekee', 'Emoo', 'Ewar', 'Udea', 'Udre', 'Ulic', 'Ucrl', 'Npbm', 'Nbrn', 'Nngs', 'Nplh', 'Nbst', 'Nalc', 'Ntin', 'Nfir'],
    'MeleeGrantItemsToHero': ['stwp'],
}

# BJ 函数名 → 中文地图特征标签（脚本命中即该图用了此机制）
BJ_FEATURES = {
    'MeleeStartingUnitsHuman': '人族对战开局',
    'MeleeStartingUnitsOrc': '兽族对战开局',
    'MeleeStartingUnitsUndead': '亡灵对战开局',
    'MeleeStartingUnitsNightElf': '暗夜对战开局',
    'MeleeStartingUnitsHumanWithoutHeroes': '人族对战开局(无英雄)',
    'MeleeStartingUnitsOrcWithoutHeroes': '兽族对战开局(无英雄)',
    'MeleeStartingUnitsUndeadWithoutHeroes': '亡灵对战开局(无英雄)',
    'MeleeStartingUnitsNightElfWithoutHeroes': '暗夜对战开局(无英雄)',
    'MeleeStartingResources': '对战起始资源',
    'MeleeStartingHeroLimit': '对战英雄上限',
    'MeleeGrantItemsToHero': '对战英雄初始物品',
    'ChooseRandomItemBJ': '随机物品',
    'ChooseRandomItemExBJ': '随机物品(按等级)',
    'InitNeutralBuildings': '中立建筑(商店/酒馆等)',
}

# bj_*_CODE 命名常量 → 对象码（电梯等）
BJ_CODE_CONSTANTS = {
    'bj_ELEVATOR_BLOCKER_CODE': 'DTep',
    'bj_ELEVATOR_CODE01': 'DTrf',
    'bj_ELEVATOR_CODE02': 'DTrx',
}
