"""Legacy manifest-test entry point composed from cohesive test responsibilities."""

from __future__ import annotations

from tests import test_batch_manifest_parser as _parser
from tests import test_batch_manifest_publication as _publication


test_manifest_round_trip_binds_every_regular_artifact = (
    _parser.test_manifest_round_trip_binds_every_regular_artifact
)
test_manifest_round_trip_retains_every_split_icon_counter = (
    _parser.test_manifest_round_trip_retains_every_split_icon_counter
)
test_manifest_parser_rejects_legacy_state_that_disagrees_with_axes = (
    _parser.test_manifest_parser_rejects_legacy_state_that_disagrees_with_axes
)
test_manifest_parser_rejects_icon_gap_claimed_as_complete_knowledge = (
    _parser.test_manifest_parser_rejects_icon_gap_claimed_as_complete_knowledge
)
test_manifest_parser_rejects_impossible_persisted_evidence_counts = (
    _parser.test_manifest_parser_rejects_impossible_persisted_evidence_counts
)
test_publication_validation_accepts_exact_manifest_fixture = (
    _publication.test_publication_validation_accepts_exact_manifest_fixture
)
test_publication_validation_rejects_same_size_tampering = (
    _publication.test_publication_validation_rejects_same_size_tampering
)
test_publication_validation_rejects_unlisted_regular_file = (
    _publication.test_publication_validation_rejects_unlisted_regular_file
)
test_publication_validation_rejects_symlink_artifact = (
    _publication.test_publication_validation_rejects_symlink_artifact
)
test_publication_validation_rejects_report_count_drift = (
    _publication.test_publication_validation_rejects_report_count_drift
)
test_publication_validation_rejects_schema_five_evidence_report_drift = (
    _publication.test_publication_validation_rejects_schema_five_evidence_report_drift
)
test_manifest_builder_rejects_duplicate_casefolded_paths = (
    _publication.test_manifest_builder_rejects_duplicate_casefolded_paths
)
